name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to Registry
        uses: egorKashirin/top-app@main
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/egorKashirin/top-app/top-app
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
          tags: "develop"